### ISSUE TITLE
Issue in Textool Sockets?

### ISSUE THREAD

**Issue by jbtronics** [KiCad/Sockets.pretty#5] opened 2016-01-04 14:29 UTC
Why do all textool sockets have irregular Pin distances? Is this desired or an Issue?

**Comment by CarlPoirier** [comment] 2016-01-16 21:47
Hi,

Can you be more specific? Which footprint is concerned? I checked one and the pins are spaced 2.54mm apart which is normal.

**Comment by evanshultz** [comment] 2017-08-03 19:11
@jbtronics I took a look at this. I'm really not sure what the problem is either. Can you add some details?

It looks like the product page for these sockets is at http://solutions.3m.com/wps/portal/3M/en_US/Interconnect/Home/Products/ProductCat/~?N=8705116&rt=r3&Nao=0, and while I haven't used them before and aren't so familiar I don't see any part families that fit these footprints.

I do see something that's odd, but it's about pad size and not pad distance:
![image](https://user-images.githubusercontent.com/1936989/28938709-c11e6c00-7843-11e7-8670-b076f8a8c340.png)

It seems the X and Y dimensions have have been converted from another unit system or are using excessive resolution. At any rate, that's odd but not necessarily a problem with using these footprints.

I'll leave this issue open for 2 days in case you want to respond or clarify the problem. If there's no comment I'll close this issue.

**Comment by evanshultz** [comment] 2017-08-07 15:56
@CarlPoirier @SchrodingersGat @jkriege2 
Last chance. I'm closing this case tomorrow if there are no comments here.

**Comment by evanshultz** [comment] 2017-08-08 22:46
And... we're done. Bye bye.

**Closed by evanshultz** 2017-08-08 22:46 UTC
